-- 069_v3_c3_anonymous_mode.sql
--
-- V3 C3 — Anonymous mode foundation (2026-05-21).
--
-- Connect tab stays hidden (feedback_connect_tab_hidden memory), so this
-- migration ships the foundation WITHOUT any user-facing exposure today.
-- When Connect re-enables, anonymous mode is ready to use.
--
-- What this adds:
-- (1) users.anonymous_mode_default — per-user opt-in. When TRUE, every
--     room the user joins automatically gets an anonymous identity
--     generated on first message (handled by client + alias-gen edge fn).
--     Default FALSE — speaking under your real name is the default; anon
--     is opt-in.
-- (2) upsert_anon_identity(room_id, alias, avatar_seed) — idempotent
--     insert that handles both first-time creation and regeneration.
--     Returns the row so the client can update its local state without
--     a second roundtrip.
-- (3) get_my_anon_identity(room_id) — returns the existing identity for
--     a room, or NULL. Used by RoomChatScreen on mount to decide whether
--     to render anon-style bubbles for this user's outgoing messages.
-- (4) list_my_anon_identities() — for the future AnonymousOnboardingScreen
--     "your aliases" view. Returns alias + room slug pairs across all
--     rooms the user has spoken in anonymously.
--
-- The existing UNIQUE(room_id, user_id) on user_anonymous_identities
-- means one alias per room per user; regeneration UPDATEs in place
-- rather than creating duplicates. This is intentional — if you
-- regenerate "TulipMama" → "WillowWarrior", existing messages in that
-- room get reattributed to the new alias on render (we join by user_id
-- not by alias, so message authorship history is preserved at the
-- pseudonymity layer).

-- ── (1) Per-user opt-in flag ─────────────────────────────────────
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS anonymous_mode_default BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN users.anonymous_mode_default IS
  'V3 C3 — when TRUE, joining a new community room auto-generates an anonymous identity for this user. Set via AnonymousOnboardingScreen (mobile). Existing room identities are not retroactively created — only forward-looking joins.';


-- ── (2) upsert_anon_identity ─────────────────────────────────────
-- Caller provides the alias + avatar seed (generated by the alias-gen
-- edge fn, not here — DB stays Claude-API-agnostic). On UNIQUE
-- (room_id, user_id) conflict, UPDATEs the existing row (this is what
-- "regenerate" does). Returns the row so the client doesn't need a
-- second fetch.
CREATE OR REPLACE FUNCTION upsert_anon_identity(
  p_room_id      UUID,
  p_alias        TEXT,
  p_avatar_seed  TEXT
) RETURNS user_anonymous_identities
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_row user_anonymous_identities;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  -- Verify the user is a member of the room before letting them claim
  -- an alias in it. Defense in depth — the existing RLS on
  -- user_anonymous_identities (USING(FALSE)) blocks direct INSERTs
  -- from the client, but SECURITY INVOKER on this RPC means we still
  -- get the auth.uid() check for the membership lookup.
  IF NOT EXISTS (
    SELECT 1 FROM room_members
    WHERE room_id = p_room_id AND user_id = v_uid
  ) THEN
    RAISE EXCEPTION 'not a member of room %', p_room_id;
  END IF;

  -- Alias collision check — within a room, every alias must be unique.
  -- The edge fn handles regeneration on collision (re-prompts Claude),
  -- but if the caller provides a colliding alias we bounce it.
  IF EXISTS (
    SELECT 1 FROM user_anonymous_identities
    WHERE room_id = p_room_id
      AND anon_alias = p_alias
      AND user_id <> v_uid
  ) THEN
    RAISE EXCEPTION 'alias % already taken in this room', p_alias;
  END IF;

  INSERT INTO user_anonymous_identities (room_id, user_id, anon_alias, anon_avatar_seed)
  VALUES (p_room_id, v_uid, p_alias, p_avatar_seed)
  ON CONFLICT (room_id, user_id) DO UPDATE
    SET anon_alias       = EXCLUDED.anon_alias,
        anon_avatar_seed = EXCLUDED.anon_avatar_seed
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;
REVOKE EXECUTE ON FUNCTION upsert_anon_identity(UUID, TEXT, TEXT) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION upsert_anon_identity(UUID, TEXT, TEXT) TO authenticated, service_role;


-- ── (3) get_my_anon_identity (one room) ─────────────────────────
CREATE OR REPLACE FUNCTION get_my_anon_identity(p_room_id UUID)
RETURNS user_anonymous_identities
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_catalog
AS $$
  SELECT * FROM user_anonymous_identities
  WHERE user_id = auth.uid()
    AND room_id = p_room_id
  LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION get_my_anon_identity(UUID) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION get_my_anon_identity(UUID) TO authenticated, service_role;


-- ── (4) list_my_anon_identities ─────────────────────────────────
-- Returns the user's aliases across all rooms (joined to rooms so the
-- onboarding screen can show "TulipMama in Postpartum 0-6w" rather
-- than raw UUIDs).
CREATE OR REPLACE FUNCTION list_my_anon_identities()
RETURNS TABLE (
  room_id      UUID,
  room_name    TEXT,
  room_slug    TEXT,
  anon_alias   TEXT,
  anon_avatar_seed TEXT,
  created_at   TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_catalog
AS $$
  SELECT uai.room_id, r.name, r.slug, uai.anon_alias, uai.anon_avatar_seed, uai.created_at
  FROM user_anonymous_identities uai
  JOIN rooms r ON r.id = uai.room_id
  WHERE uai.user_id = auth.uid()
  ORDER BY uai.created_at DESC;
$$;
REVOKE EXECUTE ON FUNCTION list_my_anon_identities() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION list_my_anon_identities() TO authenticated, service_role;


-- ── (5) set_anonymous_mode_default ──────────────────────────────
-- Tiny wrapper so the mobile client doesn't need to know users.* table
-- column names. Returns the new value.
CREATE OR REPLACE FUNCTION set_anonymous_mode_default(p_enabled BOOLEAN)
RETURNS BOOLEAN
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = public, pg_catalog
AS $$
DECLARE v_uid UUID := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  UPDATE users SET anonymous_mode_default = p_enabled WHERE id = v_uid;
  RETURN p_enabled;
END;
$$;
REVOKE EXECUTE ON FUNCTION set_anonymous_mode_default(BOOLEAN) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION set_anonymous_mode_default(BOOLEAN) TO authenticated, service_role;
