-- 122_mom_tips_seed_months_3_to_12.sql
-- Mom Tips content, part 2 of 2: weeks 13 through 52.
-- 7 tips per week x 40 weeks = 280 rows. With migration 121 (weeks 0-12, 91
-- rows) this completes the set at 371 tips -- one for every day of the baby's
-- first year, plus the rollover week.
--
-- Same clinical gate as 121: EVERY ROW IS review_status='draft'. The read RPCs
-- return only 'approved', so nothing here reaches a mom until the clinical
-- reviewer passes it. Do NOT bulk-approve to see it working.
--
-- Same copy rules as 121: practical and wellness-tier only. No diagnosis, no
-- dosing, no numeric thresholds that compete with "call your provider", nothing
-- implying a baby is behind. Anywhere a real clinical decision lives -- allergen
-- introduction, whole milk at a year, car seat stage changes, medicine doses --
-- the tip deliberately routes her to her provider instead of answering it.

INSERT INTO public.mom_tips (week_number, day_index, category, title, body, locale, review_status)
SELECT v.week_number, v.day_index, v.category, v.title, v.body, 'en', 'draft'
FROM (VALUES
  (13, 0, 'sleep', 'Three months of data', 'You know her cues better than any book does now. Trust the pattern you have actually seen.'),
  (13, 1, 'you', 'Stop reading at midnight', 'Late-night searching about milestones makes everything feel urgent. Close the phone, ask in daylight.'),
  (13, 2, 'feed', 'Still just milk', 'Solids can wait. Milk or formula is the whole meal for a while yet.'),
  (13, 3, 'care', 'Sun without sunscreen', 'Shade, a hat, long sleeves. Keep her out of direct midday light rather than lotioning her up.'),
  (13, 4, 'play', 'Give her the crinkle', 'Crinkly, noisy, high-contrast. Texture is the toy, and cost is irrelevant.'),
  (13, 5, 'you', 'Reintroduce one old thing', 'A show you liked, a walk you took, a friend you dropped. Pick one and put it back.'),
  (13, 6, 'care', 'Wipe the seat straps', 'Milk gets everywhere. Check the car seat buckle before it becomes archaeology.'),
  (14, 0, 'you', 'Divide the invisible list', 'The mental load is the appointments, the sizes, the supplies. Name the items out loud so someone else can own one.'),
  (14, 1, 'sleep', 'Catnaps are still naps', 'Thirty minutes counts. Do not fight a short nap into a long one.'),
  (14, 2, 'feed', 'Drink before she does', 'Put your own glass down where you feed. Dehydration reads exactly like exhaustion.'),
  (14, 3, 'care', 'Restock in threes', 'Wipes, diapers, and whatever you ran out of last week. Buy before empty, not at empty.'),
  (14, 4, 'play', 'She has a favourite', 'Watch which object she goes back to. That preference is real and it is new.'),
  (14, 5, 'you', 'Mute the comparison feed', 'Whatever account makes you feel behind, mute it for a month. Nothing is lost.'),
  (14, 6, 'care', 'Sleep sack over blanket', 'Loose blankets stay out of the crib. A sack keeps her warm without anything over her face.'),
  (15, 0, 'sleep', 'Watch for the shift', 'Around now sleep often gets worse before it gets better. It usually means her sleep is maturing, not breaking.'),
  (15, 1, 'you', 'Prep one meal for future you', 'Double whatever you cook and freeze half. Wednesday-you will be grateful.'),
  (15, 2, 'feed', 'Longer gaps are normal', 'Stomach capacity grows. Fewer, bigger feeds is progress, not a missed meal.'),
  (15, 3, 'care', 'New size, new check', 'Every size jump, re-check the diaper fit around her legs. Most leaks are fit, not brand.'),
  (15, 4, 'play', 'Put a toy just out of reach', 'Not cruelly far. Just far enough that she has to try. That effort is the point.'),
  (15, 5, 'you', 'Name what you miss', 'Say the thing you miss from before out loud. Naming it takes most of the weight out.'),
  (15, 6, 'care', 'Photograph the dose', 'Whatever your provider tells you, photograph the instruction. Do not rely on 3am memory.'),
  (16, 0, 'you', 'Four months in', 'The stage you found hardest in month one probably is not the hard part anymore. Notice that.'),
  (16, 1, 'sleep', 'Same room, same routine', 'Consistency of place matters more than any technique. Same crib, same order, same lighting.'),
  (16, 2, 'feed', 'Watch the interest, not the calendar', 'Sitting up, watching your food, reaching for it. That is what signals readiness, not a date.'),
  (16, 3, 'care', 'Toss the cracked bottles', 'Scratched plastic and split nipples go. It is the cheapest replacement you will ever make.'),
  (16, 4, 'play', 'Sit her up supported', 'Propped against you, facing out. A whole new view changes what she will do with an hour.'),
  (16, 5, 'you', 'Ask about your own sleep', 'If you cannot sleep even when she does, tell your provider. That is a symptom, not a personality trait.'),
  (16, 6, 'care', 'One drawer, one job', 'Diapers here, clothes there, nothing shared. In the dark, muscle memory has to be enough.'),
  (17, 0, 'sleep', 'The four-month change is real', 'Sleep genuinely reorganises around now. It is developmental, it is temporary, and it is not something you caused.'),
  (17, 1, 'you', 'Lower the bar for a fortnight', 'During a regression, survival mode is the correct mode. Resume the plan after.'),
  (17, 2, 'feed', 'More night feeds can return', 'A hungrier night stretch during a growth phase is normal. It does not undo your progress.'),
  (17, 3, 'care', 'Check the rolling risk', 'Once she can roll, swaddling with arms in stops. Move to a sleep sack now, not after.'),
  (17, 4, 'play', 'Roll practice on the floor', 'Firm, flat, plenty of room. The floor is better than any equipment you can buy.'),
  (17, 5, 'you', 'Say it is hard', 'To one person, plainly, without adding that you are lucky. You are allowed the sentence on its own.'),
  (17, 6, 'care', 'Trim before the scratch', 'She has more control of her hands now, and her face pays for it. Nails weekly.'),
  (18, 0, 'you', 'Split the mental list, again', 'It drifts back. Re-divide it every month or two, out loud.'),
  (18, 1, 'sleep', 'Wake windows stretch', 'Around two hours awake is common now. Too short a window is as disruptive as too long.'),
  (18, 2, 'feed', 'Hands in the mouth is not hunger now', 'Teething and exploring look identical to hunger cues. Check the clock before you assume.'),
  (18, 3, 'care', 'Teething is drool and chewing', 'Wet shirts and gnawing on everything. A cold, clean cloth does more than most gadgets.'),
  (18, 4, 'play', 'Pass it hand to hand', 'Watch for her moving a toy between hands. That is a real coordination milestone.'),
  (18, 5, 'you', 'Book the haircut', 'Something purely for how you feel. It matters more than it sounds.'),
  (18, 6, 'care', 'Bib rotation', 'Buy more bibs than feels reasonable. Drool season has begun.'),
  (19, 0, 'sleep', 'Cap the third nap', 'As naps consolidate, a late third nap starts stealing from bedtime. Keep it short.'),
  (19, 1, 'you', 'One night out, planned', 'Put a date on it. Not spontaneous, because spontaneous never happens now.'),
  (19, 2, 'feed', 'Keep milk the main event', 'Even once solids start, milk stays the primary nutrition for a good while.'),
  (19, 3, 'care', 'Baby-proof one room first', 'Not the house. One room where she can be on the floor safely while you sit down.'),
  (19, 4, 'play', 'Repeat her sounds back', 'When she babbles, babble back. That turn-taking is the foundation of conversation.'),
  (19, 5, 'you', 'Track your own mood, roughly', 'Not a chart. Just notice if the low days are outnumbering the others, and tell someone if they are.'),
  (19, 6, 'care', 'Outlet covers, cabinet latches', 'Do it before she moves, because the day she moves you will not have time.'),
  (20, 0, 'you', 'Leave the group chat on mute', 'You do not owe every thread a reply. Mute the ones that drain you.'),
  (20, 1, 'sleep', 'Bedtime earlier than feels right', 'Overtired babies fight sleep hardest. Earlier often means faster and longer.'),
  (20, 2, 'feed', 'Bottles get faster too', 'If she finishes in five minutes and seems settled, that is efficiency, not a problem.'),
  (20, 3, 'care', 'Wash the play mat', 'Everything she lies on now goes in her mouth. Monthly, minimum.'),
  (20, 4, 'play', 'Drop the toy, hand it back', 'She will do this forty times. It is cause and effect, and it is genuinely important work.'),
  (20, 5, 'you', 'Move your body twice this week', 'Not a programme. Twice. That is the whole goal.'),
  (20, 6, 'care', 'Size up before the season', 'Check what fits before the weather turns, not the morning it does.'),
  (21, 0, 'sleep', 'Protect one nap properly', 'Pick the nap you will always do at home, in the dark. Let the others happen wherever.'),
  (21, 1, 'you', 'Cancel the thing you dread', 'There is one obligation on your calendar you are dreading. You can cancel it.'),
  (21, 2, 'feed', 'Sitting supported to eat', 'When solids start, upright and supported matters more than what is on the spoon.'),
  (21, 3, 'care', 'Photograph the med cabinet', 'Before you need it at 2am, know what is in there and what has expired.'),
  (21, 4, 'play', 'Mirror games get better', 'She is starting to react to her reflection. Sit with her and watch her work it out.'),
  (21, 5, 'you', 'Ask a specific person, a specific thing', 'Vague asks get vague answers. Name the person, the task, the time.'),
  (21, 6, 'care', 'Two sets of keys', 'You will lock yourself out with a baby in your arms. Prepare for it now.'),
  (22, 0, 'you', 'Five months of evidence', 'Look at a photo from week one. You have learned an enormous amount without noticing.'),
  (22, 1, 'sleep', 'The dark matters most', 'Darker than feels necessary. Light is the single biggest nap disruptor.'),
  (22, 2, 'feed', 'Iron comes up soon', 'Around six months, iron-rich first foods come up with your provider. Worth asking at the next visit.'),
  (22, 3, 'care', 'Check the high chair straps', 'Before the first meal, not during it. Five-point, snug, every time.'),
  (22, 4, 'play', 'She reaches with intent', 'Give her choices and let her pick. Preference is a form of communication.'),
  (22, 5, 'you', 'Claim one end of the day', 'Mornings or nights, pick one and make fifteen minutes of it yours. Then defend it.'),
  (22, 6, 'care', 'Label the bag', 'Name and number on the diaper bag. It gets left behind eventually.'),
  (23, 0, 'sleep', 'A stir is not a wake-up', 'A brief noise at night is not an invitation. Wait a minute before you go in.'),
  (23, 1, 'you', 'Put the appointment in the calendar', 'Yours, not hers. If it is not in the calendar it is not happening.'),
  (23, 2, 'feed', 'Messy is the method', 'Hands in the food is how she learns texture. Put a mat down and let it be disgusting.'),
  (23, 3, 'care', 'Wipe the teething toys daily', 'Everything that goes in her mouth gets washed. Daily, not weekly.'),
  (23, 4, 'play', 'Read the same book again', 'Repetition is not boredom to her. It is how the words stick.'),
  (23, 5, 'you', 'Tell your partner the true number', 'Not fine. The actual number out of ten. It changes the conversation.'),
  (23, 6, 'care', 'Bag for the car, bag for the house', 'Two smaller kits beat one perfect bag you forgot.'),
  (24, 0, 'you', 'Halfway to one', 'Six months. Whatever you were told would be permanent about month one is already gone.'),
  (24, 1, 'sleep', 'Two naps is coming', 'Most babies drop toward two naps sometime in the next couple of months. Follow her, not a chart.'),
  (24, 2, 'feed', 'Start slow, start boring', 'One food at a time, a few days apart. It makes any reaction easy to spot.'),
  (24, 3, 'care', 'Allergen questions go to your provider', 'When and how to introduce common allergens is a conversation with her doctor, not the internet.'),
  (24, 4, 'play', 'Sitting frees her hands', 'Everything she can now do with two hands at once is new. Give her room to try.'),
  (24, 5, 'you', 'Plan the return, if there is one', 'If you are going back to work, start the logistics now. Not the week before.'),
  (24, 6, 'care', 'Freeze the puree in cubes', 'An ice tray gives you portioned meals with zero extra effort.'),
  (25, 0, 'sleep', 'Every new skill costs a night', 'Rolling, sitting, crawling. Expect a few rough nights with each one and do not read it as failure.'),
  (25, 1, 'you', 'Handoff sheet for whoever helps', 'Write the routine down once. It saves the same conversation forty times.'),
  (25, 2, 'feed', 'Water in an open cup', 'Small sips with meals. An open cup is a skill worth starting early.'),
  (25, 3, 'care', 'Lower the crib, now', 'The moment she can push onto her hands, the mattress drops.'),
  (25, 4, 'play', 'Bang two things together', 'Loud, repetitive, maddening, and a genuine motor milestone. Let her.'),
  (25, 5, 'you', 'Say yes to one offer', 'Someone has offered to help. Say yes to the next one without qualifying it.'),
  (25, 6, 'care', 'Second kit at work', 'If you are pumping at work, keep a full duplicate set there. Forgetting one part ruins a day.'),
  (26, 0, 'you', 'Six months of her, six months of you', 'You have been a mother exactly as long as she has been alive. You are both learning at the same speed.'),
  (26, 1, 'sleep', 'Night weaning is not a deadline', 'Some babies drop night feeds now, some much later. Neither is a scoreboard.'),
  (26, 2, 'feed', 'Let her feed herself something', 'Soft, big enough to hold, easy to gum. Control over one item changes the whole meal.'),
  (26, 3, 'care', 'Gums get brushed too', 'A soft cloth or brush once a day, before teeth arrive. It builds the habit early.'),
  (26, 4, 'play', 'Hide the toy under the cloth', 'She is starting to know it still exists. Watch her lift the cloth, because that is a leap.'),
  (26, 5, 'you', 'Book the dentist', 'Yours. Pregnancy and the first six months are hard on teeth and it always gets skipped.'),
  (26, 6, 'care', 'Stair gates before she crawls', 'Install them the week before you think you need them.'),
  (27, 0, 'sleep', 'Consistency beats method', 'Whichever approach you choose, doing it the same way for a week beats switching every night.'),
  (27, 1, 'you', 'Protect the first hour back', 'If you have returned to work, the first hour home is hers. Everything else can wait.'),
  (27, 2, 'feed', 'Three meals is a direction, not a rule', 'Build toward it over weeks. Milk is still doing the heavy lifting.'),
  (27, 3, 'care', 'Round food is the risk', 'Round, hard and coin-sized is the shape to watch. Ask your provider how to prepare each new food.'),
  (27, 4, 'play', 'Roll a ball to her', 'Rolling something back and forth teaches turn-taking better than any toy that does it for her.'),
  (27, 5, 'you', 'One thing you did well today', 'Say it out loud. It feels ridiculous and it works.'),
  (27, 6, 'care', 'Schedule on the fridge', 'Stick the medicine and feed schedule up. Whoever is on duty should not have to ask.'),
  (28, 0, 'you', 'The seven-month drag', 'Novelty has worn off and it is still relentless. This is a known dip, not a personal failure.'),
  (28, 1, 'sleep', 'Naps in the cot, not the car', 'Where you can. Motion naps are shorter and less restorative.'),
  (28, 2, 'feed', 'She will refuse things', 'A rejected food is not a permanent verdict. Offer it again in a week without comment.'),
  (28, 3, 'care', 'Teething does not cause everything', 'High fever and real illness are not teething. Those go to your provider.'),
  (28, 4, 'play', 'Name the body parts', 'Nose, hand, foot, while you dress her. Repetition plus touch is how vocabulary starts.'),
  (28, 5, 'you', 'Half an hour, door closed', 'Not asleep. Just alone. Ask for it explicitly.'),
  (28, 6, 'care', 'Rotate the toys', 'Put half away. Bring them back in a fortnight and they are new again.'),
  (29, 0, 'sleep', 'Separation anxiety hits sleep', 'Around now she may protest being put down more. That is attachment developing, not regression.'),
  (29, 1, 'you', 'You can leave and come back', 'Short goodbyes, clearly said, then go. Sneaking out is harder on both of you.'),
  (29, 2, 'feed', 'Let her hold the spoon', 'She will not use it well for months. Holding it is the practice.'),
  (29, 3, 'care', 'Recheck the room, standing up', 'What was safe when she sat is not safe now she moves. Get down on the floor and look again.'),
  (29, 4, 'play', 'Knock it down first', 'She will knock towers over long before she builds them. Knocking down is the first half of the skill.'),
  (29, 5, 'you', 'Write down one thing she did', 'A note on your phone. You will not remember this week otherwise.'),
  (29, 6, 'care', 'Shoes are not needed yet', 'Bare feet or soft socks until she is walking outdoors. Grip comes from toes.'),
  (30, 0, 'you', 'Say the resentment out loud', 'If you are keeping score in your head about who does more, say it. Silent scoring corrodes.'),
  (30, 1, 'sleep', 'Same bedtime, seven nights', 'Weekends included. The rhythm is what does the work.'),
  (30, 2, 'feed', 'Sit and eat with her', 'Even one shared meal a day. She learns eating by watching you do it.'),
  (30, 3, 'care', 'Check the car seat height again', 'Straps at or above the shoulders now that she is bigger. Recheck monthly.'),
  (30, 4, 'play', 'Container and objects', 'A bowl and some safe items. In, out, in, out. Better than most bought toys.'),
  (30, 5, 'you', 'Drop the guilt about screens', 'Your screen time is not the issue. Yours is how you stay sane.'),
  (30, 6, 'care', 'Quarter anything round', 'Grapes, cherry tomatoes, anything that shape. Cut lengthwise, then again. Highest-value habit at this stage.'),
  (31, 0, 'sleep', 'The false start', 'A wake-up 45 minutes after bedtime usually means bedtime was too late. Try earlier.'),
  (31, 1, 'you', 'One weekend morning off', 'Alternate lie-ins if there are two of you. Formalise it so it is not negotiated every week.'),
  (31, 2, 'feed', 'Textures, not just puree', 'Lumpier food now. Waiting too long makes texture harder to accept later.'),
  (31, 3, 'care', 'Move the cleaning products', 'Up high, latched, today. Crawling changes the whole risk map.'),
  (31, 4, 'play', 'Peekaboo, properly', 'She now expects you to come back. That expectation is the game.'),
  (31, 5, 'you', 'Find a mom at the same week', 'Not ahead, not behind. Same week. It is the most useful conversation there is.'),
  (31, 6, 'care', 'Nightlight, not overhead', 'For night changes and checks. Overhead light wakes her all the way up.'),
  (32, 0, 'you', 'Eight months in', 'Count what she can do now that she could not at four months. That is your work as much as hers.'),
  (32, 1, 'sleep', 'Practice in the day', 'New skills wake her at night. Give her floor time to practice crawling or pulling up during daylight.'),
  (32, 2, 'feed', 'Milk before solids, still', 'Order matters less than the total. She still needs the milk.'),
  (32, 3, 'care', 'Fridge magnets come down', 'Anything smaller than her fist, above her reach. Today.'),
  (32, 4, 'play', 'Push, do not hand', 'Slide the toy toward her rather than placing it. Movement invites her to move.'),
  (32, 5, 'you', 'Say one thing you want this year', 'Out loud, to someone. Not for her. For you.'),
  (32, 6, 'care', 'Emergency numbers on the fridge', 'Provider, poison control, and one neighbour. On paper, not just in your phone.'),
  (33, 0, 'sleep', 'Pulling up in the cot', 'She will stand and then not know how to get down. Practising sitting from standing in the day fixes it faster than going in at night.'),
  (33, 1, 'you', 'The house can be untidy', 'A tidy house and a rested mother are not both available today. Choose the second one.'),
  (33, 2, 'feed', 'Finger food over spoon food', 'Strips she can hold beat purees she cannot control. Let her run more of the meal.'),
  (33, 3, 'care', 'Cupboard she is allowed', 'Give her one low cupboard with safe things in it. She will leave the others alone more.'),
  (33, 4, 'play', 'Point at things', 'Pointing is a huge communication milestone. Point first, and she will copy.'),
  (33, 5, 'you', 'Text the friend you dropped', 'One message, no explanation for the silence. Most friendships survive being neglected.'),
  (33, 6, 'care', 'Wipe the high chair seams', 'Food gets into the crevices. Once a week, take the tray off properly.'),
  (34, 0, 'you', 'Stranger wariness is normal', 'She may suddenly refuse familiar people. It is developmental, it is not rudeness, and it fades.'),
  (34, 1, 'sleep', 'Do not start a new habit at 3am', 'Whatever you do at 3am, you are teaching. Choose the thing you can sustain.'),
  (34, 2, 'feed', 'Let her be full', 'Turning her head away means done. Pushing past it teaches her to ignore her own signal.'),
  (34, 3, 'care', 'Check the gate latches', 'Test them monthly. They loosen and you will not notice until it matters.'),
  (34, 4, 'play', 'Songs with actions', 'Hand movements with a repeated song. She will do the action before she can sing.'),
  (34, 5, 'you', 'Say no without a reason', 'No is a complete answer. You do not owe an explanation for declining.'),
  (34, 6, 'care', 'Nails, and the other set', 'Toenails get forgotten until they catch. Add them to the routine.'),
  (35, 0, 'sleep', 'Naps shorten before they merge', 'When one nap goes short and stays short, she may be heading toward two. Follow it for a week before deciding.'),
  (35, 1, 'you', 'Book something in eight weeks', 'Far enough away that it feels possible. Close enough that you will actually go.'),
  (35, 2, 'feed', 'Milk in a cup, gradually', 'Start offering some milk in a cup at one meal. No deadline, just exposure.'),
  (35, 3, 'care', 'Photograph her shoes size', 'Feet change fast and you will be in the shop guessing. Note it down.'),
  (35, 4, 'play', 'Two objects, one hand each', 'Watch her bang, compare, choose. That comparing is real cognitive work.'),
  (35, 5, 'you', 'Notice the resentment target', 'If you are angry at your partner every evening at the same time, the problem is the hour, not the person. Change the hour.'),
  (35, 6, 'care', 'Bath toys get mould', 'Squeeze them out and check inside. Bin the ones you cannot dry.'),
  (36, 0, 'you', 'Nine months out, nine months in', 'She has now been outside as long as she was inside. That is worth a moment.'),
  (36, 1, 'sleep', 'Protect the wake window before bed', 'Too long awake before bed backfires. Keep the last stretch shorter than the others.'),
  (36, 2, 'feed', 'Three meals, one snack', 'A loose shape, not a schedule. Milk still matters alongside it.'),
  (36, 3, 'care', 'Cover the sharp corners', 'Coffee table height is now head height. Do it before the first bump, not after.'),
  (36, 4, 'play', 'Give her a real object', 'A wooden spoon, a plastic bowl, an empty box. She prefers your things and she is right to.'),
  (36, 5, 'you', 'One friendship, actively maintained', 'Pick one and put effort in. Breadth costs more than you have; depth does not.'),
  (36, 6, 'care', 'Check smoke alarms', 'You are home more than ever. Test them this week.'),
  (37, 0, 'sleep', 'A wake-up is not a new problem', 'One bad night after weeks of good ones is a blip. Do not redesign the whole routine over it.'),
  (37, 1, 'you', 'Say the thing at the appointment', 'Whatever you keep meaning to ask your provider, write it on your phone now so you actually ask it.'),
  (37, 2, 'feed', 'Let her use her hands, always', 'Utensils come later. Hands are the tool she has and the practice she needs.'),
  (37, 3, 'care', 'Look for the pincer grip', 'Thumb and forefinger picking up something small. It changes what is safe on the floor.'),
  (37, 4, 'play', 'Put things in, take things out', 'A box and objects. She will do it for twenty minutes and it is real learning.'),
  (37, 5, 'you', 'Take the photo you are in', 'You are behind the camera in every picture. Hand it over and get in one.'),
  (37, 6, 'care', 'Check her sleep sack size', 'Too big is a risk, too small wakes her. Recheck at each growth spurt.'),
  (38, 0, 'you', 'You are allowed to be bored', 'Loving her and finding the days repetitive are not in conflict. Boredom is not a verdict on your love.'),
  (38, 1, 'sleep', 'Wind-down starts before the cot', 'The ten minutes before bed set the tone. Lights down, voices down, screens away.'),
  (38, 2, 'feed', 'Offer, do not push', 'Your job is what and when. Hers is whether and how much. Holding that line saves years of mealtime fights.'),
  (38, 3, 'care', 'Second-hand check', 'Anything passed to you, check for recalls before use. Especially anything she sleeps or sits in.'),
  (38, 4, 'play', 'Hide it while she watches', 'Under a cloth, in your hand, behind your back. She will look for it now, and looking is the milestone.'),
  (38, 5, 'you', 'Change one thing about the evening', 'If the same hour is hard every day, change the shape of it rather than trying harder.'),
  (38, 6, 'care', 'Trim the bag again', 'It has refilled with things you do not use. Empty it out.'),
  (39, 0, 'sleep', 'The nine-month wobble', 'Crawling, standing and separation anxiety often land together and sleep pays for it. It settles.'),
  (39, 1, 'you', 'Ask for the specific night', 'Not help in general. This Thursday, from seven, so you can sleep. Specific asks get answered.'),
  (39, 2, 'feed', 'Cup at every meal', 'Not instead of anything. Just present, every time, until it is normal.'),
  (39, 3, 'care', 'Blind cords, up and tied', 'Looped cords at crawling height are a real hazard. Tie them out of reach today.'),
  (39, 4, 'play', 'Give a running commentary', 'Narrate what she is doing as she does it. Language lands best attached to action.'),
  (39, 5, 'you', 'Check in on the relationship', 'If there are two of you, one honest conversation this month that is not logistics.'),
  (39, 6, 'care', 'Wash the car seat cover', 'Follow the manual, not your instinct. Some covers cannot go in the machine.'),
  (40, 0, 'you', 'Ten months', 'Two months from a year. Whatever you thought you would have figured out by now, you have figured out different things.'),
  (40, 1, 'sleep', 'Do not drop the second nap early', 'Most babies need two naps well past a year. A rough patch is rarely a sign to drop one.'),
  (40, 2, 'feed', 'Let the meal be short', 'Ten minutes of eating is a meal. Long sittings turn eating into a battle.'),
  (40, 3, 'care', 'Cruising means falls', 'She will pull up and edge along furniture. Clear the landing zones rather than trying to prevent it.'),
  (40, 4, 'play', 'Clap, wave, point', 'Copy her and let her copy you. These are her first real conversations.'),
  (40, 5, 'you', 'Put your appointment first', 'Book yours before hers this month. It is the only way it happens.'),
  (40, 6, 'care', 'Check the stair gate height', 'She is taller. Confirm the gate still does its job.'),
  (41, 0, 'sleep', 'Sleep is not a straight line', 'You will have a great week and then a terrible one. The trend matters, not the night.'),
  (41, 1, 'you', 'Name one thing you have got better at', 'Not about her. About you. There is at least one.'),
  (41, 2, 'feed', 'Family food, adapted', 'Cook once, adapt her portion. Separate baby meals stop being necessary sooner than you think.'),
  (41, 3, 'care', 'Bin the worn-out gear', 'The chewed bottle, the split mat, the cracked toy. Doing it in one pass is easier.'),
  (41, 4, 'play', 'Give her a container with a lid', 'On, off, on, off. It looks like nothing and it is coordination and patience together.'),
  (41, 5, 'you', 'Write the year down, badly', 'A messy paragraph about this year. Not for anyone. Future you will want it.'),
  (41, 6, 'care', 'Confirm the one-year visit', 'Book it now. It fills up and you do not want the gap.'),
  (42, 0, 'you', 'The comparison will get worse', 'Walking and talking arrive on wildly different schedules. Other babies tell you nothing about yours.'),
  (42, 1, 'sleep', 'Later bedtime rarely helps', 'When sleep gets rough the instinct is to push bedtime later. It almost always backfires.'),
  (42, 2, 'feed', 'Let her get messy again', 'Self-feeding gets worse before it gets better. That is practice, not regression.'),
  (42, 3, 'care', 'Check what she can reach standing', 'Do a lap of the house at her new height. Everything moves up a shelf.'),
  (42, 4, 'play', 'Roll, throw, drop, repeat', 'She is testing what objects do. Give her safe things to test with.'),
  (42, 5, 'you', 'Ask what your partner needs', 'Not just what you need. The question opens a better conversation than the statement.'),
  (42, 6, 'care', 'Photograph the label again', 'Sizing has drifted. Note what actually fits her now.'),
  (43, 0, 'sleep', 'Keep the routine when travelling', 'The order matters more than the place. Same three steps, wherever you are.'),
  (43, 1, 'you', 'Say no to the birthday pressure', 'A first birthday can be four people and a cake. Nothing about it needs to be an event.'),
  (43, 2, 'feed', 'Allergen foods stay in rotation', 'Once introduced, keep them regular rather than occasional. Ask your provider how often.'),
  (43, 3, 'care', 'Check the high chair again', 'She can push against the footrest now. Confirm it still cannot tip.'),
  (43, 4, 'play', 'Books with flaps', 'Lifting a flap is anticipation plus motor skill. She will do the same page ten times.'),
  (43, 5, 'you', 'Let one tradition go', 'Something you have always done that no longer fits this year. You can skip it once.'),
  (43, 6, 'care', 'Sun hat, again', 'She pulls it off now. Get the kind with a chin strap and accept the fight.'),
  (44, 0, 'you', 'Eleven months', 'One month out. Look at what she was doing at six months, not last week.'),
  (44, 1, 'sleep', 'Standing in the cot at 2am', 'She can stand but not settle back down. Practise lowering herself in the day and it resolves faster.'),
  (44, 2, 'feed', 'Milk starts to shift', 'Around a year, the balance moves toward food. Your provider will steer the specifics.'),
  (44, 3, 'care', 'First shoes when she walks outside', 'Not before. Soft, flexible, room at the toe. Indoors, bare feet still win.'),
  (44, 4, 'play', 'Give her two of the same', 'Two cups, two blocks. Matching and comparing is a new game to her.'),
  (44, 5, 'you', 'Plan the birthday you want', 'Not the one you have seen online. Small is a valid choice, not a compromise.'),
  (44, 6, 'care', 'Check the crib mattress, lowest', 'If it is not at the bottom setting, drop it now.'),
  (45, 0, 'sleep', 'One nap is coming, not yet', 'Most babies move to one nap somewhere after a year. Do not rush it because of one bad week.'),
  (45, 1, 'you', 'Ask for the birthday help', 'If you are hosting anything, delegate three specific things now.'),
  (45, 2, 'feed', 'She will eat less some days', 'Appetite swings wildly at this age. Look at the week, not the meal.'),
  (45, 3, 'care', 'Check the dog and the baby', 'Whatever animal is in the house, supervise every interaction now that she moves fast.'),
  (45, 4, 'play', 'Push toys over ride-ons', 'Something to push while walking beats something to sit in. Pushing builds the balance.'),
  (45, 5, 'you', 'Notice what is easier', 'Compare a Tuesday now with a Tuesday six months ago. The difference is the point.'),
  (45, 6, 'care', 'Pack a bag for the party', 'Whatever you are doing for her birthday, prep the day before. You will be busy.'),
  (46, 0, 'you', 'Nearly a year of this', 'You have done a full cycle of seasons, illnesses, growth spurts and regressions. That is the qualification.'),
  (46, 1, 'sleep', 'Hold the routine through the birthday', 'Late nights and excitement wreck sleep for days. Keep bedtime where it is.'),
  (46, 2, 'feed', 'Cake is optional', 'There is no requirement for a smash cake or any cake. Do what fits your family.'),
  (46, 3, 'care', 'Check the toy age labels', 'Age ratings are choking guidance, not skill guidance. Follow them for anything with small parts.'),
  (46, 4, 'play', 'Let her lead for ten minutes', 'No suggestions, no redirecting. Follow what she picks up. It is harder than it sounds.'),
  (46, 5, 'you', 'Say thank you to one person', 'Someone got you through this year. Tell them specifically what they did.'),
  (46, 6, 'care', 'Photograph the same spot', 'The chair, the blanket, the doorway. Same frame as month one, side by side.'),
  (47, 0, 'sleep', 'Consistency through the disruption', 'Visitors, travel and excitement all hit sleep. Return to the routine the next night, not the next week.'),
  (47, 1, 'you', 'You do not have to document it', 'If you did not photograph the moment, it still happened. Being present counts more.'),
  (47, 2, 'feed', 'Let her feed herself the meal', 'Messy, slow, and entirely hers. The independence is the point of this stage.'),
  (47, 3, 'care', 'Check the car seat stage', 'Around now, ask about the next stage. Do not switch early because she looks big.'),
  (47, 4, 'play', 'Stack two, then three', 'Real stacking arrives around now. Show her once, then let her fail at it.'),
  (47, 5, 'you', 'Look at the year honestly', 'The hardest month, the best week, the thing you would do differently. Write three lines.'),
  (47, 6, 'care', 'Replace the bottle teats', 'If you are still using them, check for wear. They degrade quietly.'),
  (48, 0, 'you', 'Twelve months of decisions', 'You have made thousands of calls this year with incomplete information. That is the skill you built.'),
  (48, 1, 'sleep', 'A birthday does not change sleep', 'Nothing shifts because she turned one. The changes come when they come.'),
  (48, 2, 'feed', 'Whole milk, if your provider says', 'Around a year the milk question changes. Ask at the one-year visit rather than guessing.'),
  (48, 3, 'care', 'Bring the questions to the visit', 'Write them down beforehand. You will forget half of them in the room.'),
  (48, 4, 'play', 'Words are coming', 'Some babies have several, some have none yet. Both are within normal. Keep talking to her.'),
  (48, 5, 'you', 'Decide what you keep', 'Of everything you did this year, what is worth carrying into the next one? Drop the rest.'),
  (48, 6, 'care', 'Store the newborn gear or pass it on', 'Decide deliberately rather than letting it sit in the hall for six months.'),
  (49, 0, 'sleep', 'The first-year sleep myth', 'Very few one-year-olds sleep perfectly through. If yours does not, you are in the majority.'),
  (49, 1, 'you', 'Ask for the year-two version of help', 'What you needed at month one is not what you need now. Update the ask.'),
  (49, 2, 'feed', 'Sit her at the table', 'Same table, same time, whenever you can. She learns eating socially.'),
  (49, 3, 'care', 'Check the gate at the top of the stairs', 'Now that she climbs, the top gate matters more than the bottom one.'),
  (49, 4, 'play', 'Give her a crayon', 'Big, chunky, on paper you do not care about. Scribbling is a real motor stage.'),
  (49, 5, 'you', 'Notice who showed up', 'Some people surprised you this year in both directions. Adjust your energy accordingly.'),
  (49, 6, 'care', 'Book the dentist for her', 'First tooth or first birthday, whichever came first. Ask your provider what they recommend.'),
  (50, 0, 'you', 'Stop reading ahead', 'Toddler content will make the next stage sound terrifying. Stay in the week you are in.'),
  (50, 1, 'sleep', 'Bedtime moves with daylight', 'Longer evenings shift her body clock. Blackout matters more in summer.'),
  (50, 2, 'feed', 'Let her refuse without a fight', 'Neutral face, food goes away, no negotiation. Reaction is what turns refusal into a habit.'),
  (50, 3, 'care', 'Recheck every latch and gate', 'An annual sweep. She is taller, stronger and more determined than when you installed them.'),
  (50, 4, 'play', 'Simple instructions land now', 'Bring me the cup. Put it in the box. She may follow one step, and that is new.'),
  (50, 5, 'you', 'Take the day off, if you can', 'Not to catch up on anything. A day where the goal is nothing.'),
  (50, 6, 'care', 'Photograph the medicine list', 'Doses change with weight. Confirm current guidance with your provider rather than reusing an old note.'),
  (51, 0, 'sleep', 'One nap, when she is ready', 'The signs are fighting the morning nap and coping fine without it. Move slowly and expect a rough fortnight.'),
  (51, 1, 'you', 'Write down what you want next year', 'Three things. Not resolutions. Just three things you would like to be true.'),
  (51, 2, 'feed', 'Variety over volume', 'Offer a range and stop counting. What she eats across a week is what matters.'),
  (51, 3, 'care', 'Check her shoes fit', 'A thumb width at the toe. Feet grow faster than shoes wear out.'),
  (51, 4, 'play', 'Let her help', 'Handing you the laundry, carrying a spoon to the table. It is slower and it is the whole point.'),
  (51, 5, 'you', 'Say the year out loud to someone', 'What it actually took. Not the highlights version. It deserves saying.'),
  (51, 6, 'care', 'Update the emergency numbers', 'New provider, new dentist, new neighbour. Refresh the list on the fridge.'),
  (52, 0, 'you', 'A full year', 'You kept a person alive and growing for a year while learning how, with no time off. That is the whole achievement and it does not need qualifying.'),
  (52, 1, 'sleep', 'Nothing about this is finished', 'Sleep will change again, many times. You now know that it always changes back.'),
  (52, 2, 'feed', 'She eats what you eat, mostly', 'Adapted, cut safely, but the same meal. That shift is worth marking.'),
  (52, 3, 'care', 'One safety sweep a year', 'Put it in the calendar annually. Gates, latches, cords, car seat, crib. One pass, every year.'),
  (52, 4, 'play', 'She is her own person now', 'Preferences, refusals, opinions, humour. The person you were waiting to meet has arrived.'),
  (52, 5, 'you', 'Look at week one again', 'Read the first tip you ever got here. You were a different person and you did this.'),
  (52, 6, 'care', 'Decide what year two looks like', 'Not a plan. Just one thing you want to do differently now that you know what you know.')
) AS v(week_number, day_index, category, title, body)
ON CONFLICT (week_number, day_index, locale) DO NOTHING;
