-- 129_retention_purge_home_feed_cache.sql
--
-- The first actual retention job in the database: age out the generated home
-- feed. Nothing else changes — every other retention question is still with
-- counsel (see legal/…_counsel_package.md Appendix D).
--
-- WHY THIS ONE, AND WHY NOW
-- -------------------------
-- The 2026-07-09 data-minimisation audit (gap #1) and the 2026-08-14 security
-- review (P-2) both found the same systemic hole: Villie has no retention
-- policy anywhere, and `account-delete` only stamps `deleted_at`. Verified
-- 2026-08-15 — there is not a single purge/retention/cleanup job scheduled on
-- this database. Nothing is ever deleted.
--
-- Most of that is genuinely blocked on legal: whether a postpartum mother's
-- check-in free text or an infant's feed logs may be deleted, and what account
-- deletion is allowed to remove, are not engineering calls.
--
-- `home_feed_cache` is the exception. It is a **derived cache** — AI-curated
-- cards regenerated daily by `home-feed-curator`, already carrying its own
-- `expires_at`, reconstructible at any time from the source data. Deleting an
-- expired row destroys no record of anything. It needs no legal sign-off, so
-- it should not sit behind one.
--
-- It is not nothing, either: the cards are *personalised* — milestone copy,
-- check-in state, stage-matched perks — so they are a small derived projection
-- of the sensitive data. Before this migration the oldest row was generated
-- 2026-05-28 and 6 of 11 rows were more than a week past expiry: roughly two
-- and a half months of stale personalised content for users who may not have
-- opened the app since.
--
-- WHY A 7-DAY GRACE, NOT "DELETE ON EXPIRY"
-- -----------------------------------------
-- `get_home_feed()` deliberately returns expired rows with `is_stale = TRUE`,
-- and the client renders that stale feed while refreshing in the background.
-- Purging exactly at `expires_at` would therefore turn "slightly stale feed,
-- refreshing" into "empty screen" for anyone whose cache lapsed. The TTL is
-- 24 h, so a row 7 days past expiry is ~8 days old and belongs to someone who
-- has not opened the app in a week — for her, regenerating is better than
-- showing week-old cards anyway. The grace period is a parameter so it can be
-- tightened without another migration.
--
-- WHY pg_cron AND NOT THE GITHUB ACTIONS WORKFLOW
-- -----------------------------------------------
-- Most pg_cron jobs here are dead: they call `net.http_post` with
-- `current_setting('app.supabase_url')`, which the Free-tier GUC lock makes
-- throw, which is why `.github/workflows/supabase-crons.yml` exists. Confirmed
-- against `cron.job_run_details` on 2026-08-15: every HTTP-callout job has
-- FAILED on every run, while the pure-SQL jobs (`gear-moderation-p0-auto-
-- withdraw`, `daily-checkin-reminder`) have succeeded on all 288 and 3 runs
-- respectively. This job is pure SQL and calls no edge function, so pg_cron is
-- the correct and simplest home for it — no secret, no HTTP, nothing to break.

BEGIN;

CREATE OR REPLACE FUNCTION public.purge_expired_home_feed_cache(p_grace_days INT DEFAULT 7)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $fn$
DECLARE
  v_deleted INT;
BEGIN
  DELETE FROM home_feed_cache
  WHERE expires_at < now() - make_interval(days => GREATEST(COALESCE(p_grace_days, 7), 0));

  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$fn$;

COMMENT ON FUNCTION public.purge_expired_home_feed_cache(INT) IS
  'Retention: deletes home_feed_cache rows more than p_grace_days past expires_at. '
  'Safe to run any time — the feed is a derived cache regenerated by home-feed-curator. '
  'The grace period exists because get_home_feed() serves stale rows while refreshing; '
  'see migration 129.';

-- Ops-only, matching the posture of migrations 052/054: no client ever calls this.
REVOKE EXECUTE ON FUNCTION public.purge_expired_home_feed_cache(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.purge_expired_home_feed_cache(INT) FROM anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.purge_expired_home_feed_cache(INT) TO service_role;

-- Schedule daily at 08:20 UTC (04:20 ET) — a slot no other job occupies, and
-- comfortably after the 09:10 UTC curator run has stopped mattering for the day.
DO $sched$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'home-feed-cache-purge') THEN
      PERFORM cron.unschedule('home-feed-cache-purge');
    END IF;

    PERFORM cron.schedule(
      'home-feed-cache-purge',
      '20 8 * * *',
      $cron$ SELECT public.purge_expired_home_feed_cache(); $cron$
    );
  END IF;
END
$sched$;

COMMIT;
